python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_gender_no_sub_samp_project_config_bert_all.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_gender_no_sub_samp_project_config_bert_only_class.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_gender_no_sub_samp_project_config_bert_only_embedding_classification.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_gender_no_sub_samp_project_config_bert_rand_init.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_gender_no_sub_samp_project_config_ola.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_sentiment_project_config_ola.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_sentiment_project_config_bert_randomly_init_embedding_classification.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_sentiment_project_config_bert_only_embedding_classification.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_sentiment_project_config_bert_only_classification.json & \
python3 ./scripts/hydra/submit_hydra_job.py --mode xai --config /home/space/uniml/hjalmar/xai-nlp-benchmark/artifacts/xai-nlp-benchmark-2024-04-23-21-20-02/configs/par_xai_sentiment_project_config_bert_all.json
